spring:
  # 파일 이미지 용량 제한
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://host.docker.internal:3306/pojang
    url: jdbc:mariadb://localhost:3306/pojang
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jongseunghan5@gmail.com
    password: uezisesgftbxlxvb
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000 # SMTP 서버에 연결을 시도하고 응답을 기다리는 최대 시간이 50,000ms
        smtp.starttls.enable: true
  data:
    redis:
      repositories:
        # Spring data JPA repository 와 Spirng data redis Repository가 모두 인식되어
        # redis가 이게 내 리포지토리가 맞아? 그럼 명시해줘 라는 로그 해결
        enabled: false
      host: localhost
      port: 6379
  coolsms:
      apiKey: NCSW9W1WPRODZ9JV
      apiSecret: FIJRCGDMA1Y8XTJ5HY8XO3SM4N9YPJ61
      sender: 010-6717-1351
jwt:
  expiration: 30 # 30분
  secretKey: mySecret

cloud:
  aws:
    credentials:
      access-key: AKIAVBRILX2DBMCZGSG2
      secret-key: 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
    s3:
      bucket: pojang-image-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


# @Value를 사용하여 imagePath를 전역적으로 사용 가능
image:
  # bellwin: C:/Users/Playdata/OneDrive/바탕 화면/pojang_image/
  # SimJH99: C:\Users\Playdata\Desktop\프로젝트 사진 저장
#  path: C:\Users\Playdata\Desktop\프로젝트 사진 저장
#  path: C:/Users/Playdata/Desktop/pojang_image
#  path: C:/Users/Playdata/OneDrive/바탕 화면/pojang_image/
   path: C:/Users/Playdata/Desktop/pojang_image
#  path: C:\Users\USER\Desktop\playdata\image\pojang
