name: deploy k8s-pojang

on:
  # push:
  #   branches:
  #   - main
  pull_request:
    branches:
    - sy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2
      
      - name: install kubectl 
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install

      # aws κ¶ν• μ„Έν…
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{secrets.AWS_S3_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_S3_SECRET_KEY}}
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name pojang --region ap-northeast-2

      - name: Build Docker Image
        run: docker build -t bny1324/k8s-pojang:v1 .
      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image to DockerHub
        run: docker push bny1324/k8s-pojang:v1

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./k8s/pojang-depl-serv.yml
          kubectl rollout restart deployment pojang-depl

          
          